// Runs the real Next route handlers and authentication with only Supabase I/O
// replaced by a delayed in-memory compare-and-swap adapter. No network is used.
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
const {AsyncLocalStorage}=require('node:async_hooks');
const context=new AsyncLocalStorage(),cache=new Map(),report=[];
const clone=x=>structuredClone(x),delay=()=>new Promise(r=>setTimeout(r,1+Math.floor(Math.random()*4)));
let db,casMisses=0,pauseNext=null;
class Query {
  constructor(){this.filters={};}
  select(){return this;}eq(k,v){this.filters[k]=v;return this;}update(v){this.value=v;return this;}upsert(){throw new Error('Seed writes forbidden in this test');}
  async single(){return this.run();}async maybeSingle(){return this.run();}
  async run(){await delay();if(this.value&&pauseNext){const gate=pauseNext;pauseNext=null;gate.started();await gate.release;}
    if(this.filters.updated_at&&this.filters.updated_at!==db.updated_at){if(this.value)casMisses++;return {data:null,error:null};}
    if(this.value)db={...db,...clone(this.value)};
    return {data:clone(db),error:null};}
}
function load(filename){filename=path.resolve(filename);if(cache.has(filename))return cache.get(filename).exports;const m={exports:{}};cache.set(filename,m);const js=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;new Function('require','module','exports',js)((id)=>{
  if(id==='@supabase/supabase-js')return {createClient:()=>({from:()=>new Query()})};
  if(id==='next/headers')return {cookies:async()=>({get:name=>context.getStore()?.[name]?{value:context.getStore()[name]}:undefined})};
  if(id.startsWith('@/'))return load(path.resolve('src',id.slice(2)+'.ts'));
  if(id.startsWith('.'))return load(path.resolve(path.dirname(filename),id+'.ts'));
  return require(id);
},m,m.exports);return m.exports;}
process.env.SUPABASE_URL='http://local-test.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';process.env.SCHOOL_PIN='246810';process.env.ADMIN_PIN='975310';
const {defaultPermissions}=load('src/lib/permissions.ts'),{pinHash}=load('src/lib/server-auth.ts');
const routes=Object.fromEntries(['state','backup','permissions','auth/login','auth/status','auth/change-pin'].map(p=>[p,load('src/app/api/'+p+'/route.ts')]));
const student=i=>({id:'s-'+i,name:'예시학생'+i,grade:1,classNumber:1,number:i,createdAt:'2026-09-07'});
const record=(id,studentId='s-1')=>({id,studentId,type:'penalty',score:-1,reason:'수업 방해',awardedBy:'테스트교원',awardedAt:'2026-09-07T09:00:00.000Z',note:''});
const reset=()=>{db={id:'main',updated_at:new Date().toISOString(),data:{students:Array.from({length:30},(_,i)=>student(i+1)),records:[],violations:[{id:'v1',reason:'수업 방해',score:-1}],committeeHeld:{},committeeDismissed:[],settings:{pinHash:pinHash(process.env.SCHOOL_PIN),teacherPermissions:{...defaultPermissions},dataEpoch:0}}};};
async function call(session,route,method='GET',body){return context.run(session,()=>routes[route][method](new Request('http://localhost/api/'+route,{method,...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})})));}
async function login(role){const r=await call({},'auth/login','POST',{role,pin:role==='admin'?process.env.ADMIN_PIN:process.env.SCHOOL_PIN});assert.equal(r.status,200);const cookie=r.cookies.get(role==='admin'?'school_admin':'school_session');assert(cookie);return {[cookie.name]:cookie.value};}
const statusList=rs=>rs.map(r=>r.status);
async function scenario(name,fn){const start=Date.now();await fn();report.push({scenario:name,result:'PASS',localMilliseconds:Date.now()-start});console.log('PASS '+name);}
function pause(){let started,release;const start=new Promise(r=>started=r),wait=new Promise(r=>release=r);pauseNext={started,release:wait};return {start,release};}
(async()=>{
 reset();const admins=await Promise.all(Array.from({length:5},()=>login('admin'))),teachers=await Promise.all(Array.from({length:20},()=>login('teacher'))),sessions=[...admins,...teachers];
 await scenario('5 administrators + 20 teachers: 25 independent authenticated sessions',async()=>{const rs=await Promise.all(sessions.map(s=>call(s,'auth/status')));const roles=await Promise.all(rs.map(r=>r.json()));assert.equal(roles.filter(r=>r.role==='admin').length,5);assert.equal(roles.filter(r=>r.role==='teacher').length,20);});
 await scenario('25 sessions x 10 rounds: 250 simultaneous record additions, no loss',async()=>{for(let round=0;round<10;round++){const rs=await Promise.all(sessions.map((s,i)=>call(s,'state','PATCH',{type:'record:add',epoch:0,record:record(`r-${round}-${i}`)})));assert(rs.every(r=>r.status===200),JSON.stringify(statusList(rs)));}assert.equal(db.data.records.length,250);assert.equal(new Set(db.data.records.map(r=>r.id)).size,250);});
 await scenario('25 simultaneous student additions preserve all students',async()=>{const rs=await Promise.all(sessions.map((s,i)=>call(s,'state','PATCH',{type:'student:add',epoch:0,student:student(100+i)})));assert(rs.every(r=>r.status===200),JSON.stringify(statusList(rs)));assert.equal(db.data.students.length,55);});
 await scenario('25 different student edits persist without replacing whole roster',async()=>{const before=clone(db.data.students);const rs=await Promise.all(sessions.map((s,i)=>{const st=before.find(x=>x.id==='s-'+(i+1));return call(s,'state','PATCH',{type:'student:update',epoch:0,before:st,student:{...st,name:'수정'+i}});}));assert(rs.every(r=>r.status===200),JSON.stringify(statusList(rs)));for(let i=0;i<25;i++)assert.equal(db.data.students.find(x=>x.id==='s-'+(i+1)).name,'수정'+i);});
 await scenario('Same record edited by all 25: exactly 1 save, 24 explicit conflicts',async()=>{const before=clone(db.data.records[0]);const rs=await Promise.all(sessions.map((s,i)=>call(s,'state','PATCH',{type:'record:update',epoch:0,before,record:{...before,note:'변경'+i}})));assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(rs.filter(r=>r.status===409).length,24);});
 await scenario('Administrator deletion versus teacher edit: 1 success, 1 conflict',async()=>{const before=clone(db.data.records[1]);const rs=await Promise.all([call(admins[0],'state','PATCH',{type:'record:delete',epoch:0,id:before.id,before}),call(teachers[0],'state','PATCH',{type:'record:update',epoch:0,before,record:{...before,note:'경합'}})]);assert.deepEqual(statusList(rs).sort(),[200,409]);});
 await scenario('25 concurrent deletions of different records persist',async()=>{const before=clone(db.data.records.slice(5,30));const rs=await Promise.all(sessions.map((s,i)=>call(s,'state','PATCH',{type:'record:delete',epoch:0,id:before[i].id,before:before[i]})));assert(rs.every(r=>r.status===200));assert(before.every(x=>!db.data.records.some(r=>r.id===x.id)));});
 await scenario('Teacher student deletion versus new record: no orphaned records',async()=>{const before=clone(db.data.students.find(s=>s.id==='s-30'));const rs=await Promise.all([call(teachers[0],'state','PATCH',{type:'student:delete',epoch:0,id:before.id,before}),call(admins[0],'state','PATCH',{type:'record:add',epoch:0,record:record('delete-race','s-30')})]);assert.equal(rs[0].status,200);assert([200,409].includes(rs[1].status));assert(!db.data.records.some(r=>r.studentId==='s-30'));});
 await scenario('20 teachers cannot change permissions, restore, or change rules',async()=>{const snapshot=clone(db.data);const rs=await Promise.all(teachers.flatMap(s=>[call(s,'permissions','PUT',{permissions:defaultPermissions,before:defaultPermissions}),call(s,'backup','GET'),call(s,'backup','POST',{}),call(s,'state','PATCH',{type:'state:merge',epoch:0,before:{violations:snapshot.violations},data:{violations:[]}})]));assert(rs.every(r=>r.status===403),JSON.stringify(statusList(rs)));});
 await scenario('5 administrators editing permissions: 1 success, 4 explicit conflicts',async()=>{const before=clone(db.data.settings.teacherPermissions);const rs=await Promise.all(admins.map(s=>call(s,'permissions','PUT',{before,permissions:{...before,recordDelete:false}})));assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(rs.filter(r=>r.status===409).length,4);});
 await scenario('Revocation during in-flight teacher save is enforced on retry',async()=>{const gate=pause();const request=call(teachers[0],'state','PATCH',{type:'record:add',epoch:0,record:record('must-not-save')});await gate.start;const before=clone(db.data.settings.teacherPermissions);const permission=await call(admins[0],'permissions','PUT',{before,permissions:{...before,recordAdd:false}});assert.equal(permission.status,200);gate.release();assert.equal((await request).status,403);assert(!db.data.records.some(r=>r.id==='must-not-save'));const after=clone(db.data.settings.teacherPermissions);assert.equal((await call(admins[0],'permissions','PUT',{before:after,permissions:defaultPermissions})).status,200);});
 await scenario('Backup restore racing with another write refuses stale replacement',async()=>{const backup=await(await call(admins[0],'backup')).json();const expectedUpdatedAt=db.updated_at;const gate=pause();const restore=call(admins[0],'backup','POST',{backup,expectedUpdatedAt});await gate.start;assert.equal((await call(teachers[0],'state','PATCH',{type:'record:add',epoch:0,record:record('after-backup')})).status,200);gate.release();assert.equal((await restore).status,409);assert(db.data.records.some(r=>r.id==='after-backup'));});
 await scenario('Restore invalidates all 25 old browser writes, including additions',async()=>{const backup=await(await call(admins[0],'backup')).json();assert.equal((await call(admins[0],'backup','POST',{backup,expectedUpdatedAt:db.updated_at})).status,200);const rs=await Promise.all(sessions.map((s,i)=>call(s,'state','PATCH',{type:'record:add',epoch:0,record:record('stale-'+i)})));assert(rs.every(r=>r.status===409));assert.equal((await call(teachers[0],'state','PATCH',{type:'record:add',epoch:1,record:record('fresh-after-restore')})).status,200);});
 await scenario('Same student edited by all 25: exactly 1 save, 24 explicit conflicts',async()=>{const before=clone(db.data.students[0]);const rs=await Promise.all(sessions.map((s,i)=>call(s,'state','PATCH',{type:'student:update',epoch:1,before,student:{...before,name:'동시수정'+i}})));assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(rs.filter(r=>r.status===409).length,24);});
 await scenario('Stale whole-roster save cannot overwrite a newer teacher edit',async()=>{const before={students:clone(db.data.students)};const row=clone(db.data.students[1]);assert.equal((await call(teachers[0],'state','PATCH',{type:'student:update',epoch:1,before:row,student:{...row,name:'보존할 수정'}})).status,200);assert.equal((await call(admins[0],'state','PATCH',{type:'state:merge',epoch:1,before,data:{students:before.students}})).status,409);assert.equal(db.data.students.find(s=>s.id===row.id).name,'보존할 수정');});
 await scenario('Both PINs are role-specific; identical PIN configuration rejected',async()=>{assert.equal((await call({},'auth/login','POST',{role:'admin',pin:process.env.SCHOOL_PIN})).status,401);assert.equal((await call({},'auth/login','POST',{role:'teacher',pin:process.env.ADMIN_PIN})).status,401);const adminPin=process.env.ADMIN_PIN;process.env.ADMIN_PIN=process.env.SCHOOL_PIN;assert.equal((await call({},'auth/login','POST',{role:'admin',pin:process.env.ADMIN_PIN})).status,503);process.env.ADMIN_PIN=adminPin;assert.equal((await call(admins[0],'auth/change-pin','POST',{adminPin,newPin:adminPin})).status,400);});
 await scenario('Authenticated reads and backups never include PIN hash or settings',async()=>{const rs=await Promise.all(sessions.map(s=>call(s,'state')));for(const r of rs){assert.equal(r.status,200);const text=await r.text();assert(!text.includes('pinHash'));assert(!text.includes('teacherPermissions'));}const backup=await(await call(admins[0],'backup')).text();assert(!backup.includes('pinHash'));});
 const summary={createdAt:new Date().toISOString(),sessions:{admin:5,teacher:20},adapter:'Real API/auth handlers; delayed in-memory Supabase adapter. NOT production capacity testing.',casRetriesObserved:casMisses,scenarios:report};fs.writeFileSync('tests/concurrency-results.json',JSON.stringify(summary,null,2));console.log(JSON.stringify({scenarios:report.length,passed:report.length,casRetriesObserved:casMisses}));
})().catch(e=>{console.error(e);process.exitCode=1});
