"use client";
import { useState } from "react";
import { Download, ShieldCheck, HardDrive, Upload, Check } from "lucide-react";
import { permissionLabels, type Permissions, type Permission } from "@/lib/permissions";
import { parseBackup } from "@/lib/backup";

export function AdminPanel({ permissions, request, onPermissions, onRestore }: { permissions: Permissions; request: typeof fetch; onPermissions: (p: Permissions) => void; onRestore: () => void }) {
  const [draft, setDraft] = useState(permissions), [base, setBase] = useState(permissions), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [pending, setPending] = useState<{ file: unknown; name: string; students: number; records: number } | null>(null), [confirmation, setConfirmation] = useState("");
  async function run(action: () => Promise<void>) { setBusy(true); setMessage(""); try { await action(); } catch (e) { setMessage(e instanceof Error ? e.message : "작업하지 못했습니다."); } finally { setBusy(false); } }
  async function download() { const response = await request("/api/backup"); if (!response.ok) throw new Error("백업을 내려받지 못했습니다."); const blob = new Blob([JSON.stringify(await response.json(), null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `장흥중학교-백업-${new Date().toISOString().replace(/[:.]/g,"-")}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <div className="space-y-7">
    <div><p className="text-sm font-bold text-sky-700">관리자 전용</p><h1 className="mt-1 text-3xl font-extrabold">권한 관리 · 백업</h1><p className="mt-2 text-sm text-slate-500">선생님들이 필요한 기능만 사용하도록 설정하고, 학교 데이터를 보관하세요.</p></div>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]">
      <section className="card"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-sky-100 p-3 text-sky-700"><ShieldCheck/></div><div><h2 className="text-lg font-extrabold">일반 교원 권한</h2><p className="mt-1 text-xs text-slate-500">조회는 기본 허용 · 아래 권한은 일반 교원 전체에 적용</p></div></div>
        <div className="divide-y">{(Object.keys(permissionLabels) as Permission[]).map(key => <label key={key} className="flex cursor-pointer items-center justify-between gap-3 py-4"><span className="text-sm font-semibold">{permissionLabels[key]}{key==="rosterReplace"&&<span className="mt-1 block text-xs font-normal leading-5 text-amber-700">전체 명단을 바꾸거나 진급 처리하며, 기존 위반 기록을 초기화합니다.</span>}</span><span className="flex shrink-0 items-center gap-3"><span className={`text-xs font-bold ${draft[key]?"text-sky-700":"text-slate-400"}`}>{draft[key]?"허용":"제한"}</span><input aria-label={permissionLabels[key]} type="checkbox" role="switch" checked={draft[key]} disabled={busy} onChange={e => setDraft(p => ({...p,[key]:e.target.checked}))} className="h-5 w-5 accent-sky-700"/></span></label>)}</div>
        <button disabled={busy} className="primary-btn mt-5 w-full justify-center disabled:opacity-50" onClick={() => run(async () => { const r = await request("/api/permissions", {method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({permissions:draft,before:base})}); if(!r.ok) {const error=await r.json(); throw new Error(error.error||"권한을 저장하지 못했습니다.");} setBase(draft); onPermissions(draft); setMessage("일반 교원 권한을 저장했습니다."); })}><Check size={18}/>권한 저장</button><p className="mt-3 text-xs leading-5 text-slate-500">관리자 권한과 백업·복원은 일반 교원에게 부여되지 않습니다. 기록 수정 권한은 모든 교원의 기록에 적용됩니다.</p>
      </section>
      <div className="space-y-5"><section className="card"><div className="mb-4 flex items-center gap-3"><div className="rounded-xl bg-emerald-100 p-3 text-emerald-700"><HardDrive/></div><h2 className="text-lg font-extrabold">데이터 백업</h2></div><p className="text-sm leading-6 text-slate-500">학생 명단, 위반 기록, 규정 항목, 위원회 처리 현황을 JSON 파일 하나로 저장합니다.</p><div className="my-5 rounded-xl bg-slate-50 p-4 text-xs leading-6 text-slate-600">필요할 때 직접 내려받는 수동 백업입니다.<br/>로그인 정보와 권한 설정은 포함되지 않습니다.</div><button disabled={busy} onClick={() => run(async () => { await download(); setMessage("백업 다운로드를 시작했습니다. 파일을 안전한 곳에 보관해 주세요."); })} className="primary-btn w-full justify-center"><Download size={18}/>현재 데이터 백업</button></section>
      <section className="card"><h2 className="text-lg font-extrabold">백업 파일로 복원</h2><p className="mt-2 text-sm leading-6 text-slate-500">파일을 먼저 검사하고, 학생 수와 기록 수를 확인한 후 복원합니다.</p><label className="mt-5 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-sm font-bold"><Upload size={18}/>백업 파일 선택<input type="file" accept=".json,application/json" disabled={busy} className="sr-only" onChange={e => { const f=e.target.files?.[0]; e.target.value=""; if(!f)return; setPending(null); setConfirmation(""); run(async () => { if(f.size>20*1024*1024)throw new Error("20MB 이하의 파일을 선택해 주세요."); const file=JSON.parse(await f.text()), data=parseBackup(file); setPending({file,name:f.name,students:(data.students as unknown[]).length,records:(data.records as unknown[]).length}); }); }}/></label>
      {pending&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="break-all text-sm font-bold">{pending.name}</p><p className="mt-2 text-sm">학생 {pending.students}명 · 위반 기록 {pending.records}건</p><p className="mt-3 text-xs leading-5 text-amber-900">현재 데이터를 먼저 백업한 뒤 선택한 파일로 교체합니다. 아래에 ‘복원’을 입력하세요.</p><input aria-label="복원 확인" value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="field mt-3" placeholder="복원"/><div className="mt-3 flex gap-2"><button disabled={busy||confirmation!=="복원"} className="rounded-xl bg-amber-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-40" onClick={()=>run(async()=>{ const status=await request("/api/state"); if(!status.ok)throw new Error("현재 데이터를 확인하지 못했습니다."); const {updatedAt}=await status.json(); await download(); const r=await request("/api/backup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({backup:pending.file,expectedUpdatedAt:updatedAt})}); if(!r.ok)throw new Error("복원하지 못했습니다. 다른 변경이 있었는지 확인하고 다시 시도해 주세요."); setPending(null);setMessage("백업 데이터를 복원했습니다.");onRestore();})}>백업 후 복원</button><button className="px-3 text-sm" onClick={()=>setPending(null)}>취소</button></div></div>}</section></div>
    </div>{message&&<p role="status" className="rounded-xl border bg-white p-4 text-sm font-semibold">{message}</p>}
  </div>;
}
