"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Check, ChevronRight, ClipboardList, Clock3, Download, FileText, GraduationCap, LayoutDashboard, Menu, Plus, Search, Settings, ShieldCheck, UserRound, Users, X } from "lucide-react";
import { students as initialStudents, pointRecords as initialRecords } from "@/lib/mock-data";
import type { PointRecord, Student } from "@/types";

type View = "dashboard" | "students" | "records" | "report" | "settings";
const nav: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "dashboard", label: "대시보드", icon: LayoutDashboard }, { id: "students", label: "학생 관리", icon: Users },
  { id: "records", label: "위반 내역", icon: ClipboardList }, { id: "report", label: "리포트 · 내보내기", icon: FileText },
  { id: "settings", label: "규정 항목 설정", icon: Settings },
];
const violations = [
  { category: "출결", reason: "무단 지각", score: -1 }, { category: "출결", reason: "무단 결과·조퇴", score: -2 },
  { category: "수업", reason: "수업 방해", score: -2 }, { category: "생활", reason: "교내 전자기기 무단 사용", score: -2 },
  { category: "생활", reason: "복장·용의 규정 위반", score: -1 }, { category: "안전", reason: "위험 물품 소지", score: -5 },
  { category: "관계", reason: "언어폭력·모욕", score: -5 },
];
const formatDate = (value: string) => new Intl.DateTimeFormat("ko-KR", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
function StudentLabel({ student }: { student?: Student }) { return student ? <><strong>{student.name}</strong><span className="text-slate-400"> {student.grade}학년 {student.classNumber}반 {student.number}번</span></> : <span>삭제된 학생</span>; }

export function Dashboard() {
  const [view, setView] = useState<View>("dashboard"), [menuOpen, setMenuOpen] = useState(false), [modalOpen, setModalOpen] = useState(false), [saved, setSaved] = useState(false), [query, setQuery] = useState("");
  const [students] = useState<Student[]>(initialStudents), [records, setRecords] = useState<PointRecord[]>(initialRecords);
  useEffect(() => { const stored = localStorage.getItem("school-violation-records"); if (stored) setRecords(JSON.parse(stored)); }, []);
  useEffect(() => { localStorage.setItem("school-violation-records", JSON.stringify(records)); }, [records]);
  const studentTotals = useMemo(() => students.map(student => ({ ...student, penalty: Math.abs(records.filter(r => r.studentId === student.id && r.score < 0).reduce((n, r) => n + r.score, 0)), count: records.filter(r => r.studentId === student.id && r.score < 0).length })).sort((a,b) => b.penalty-a.penalty), [records, students]);
  const filteredStudents = studentTotals.filter(s => `${s.name} ${s.grade}-${s.classNumber} ${s.number}`.includes(query));
  const totalPenalty = records.filter(r=>r.score<0).reduce((n,r)=>n+Math.abs(r.score),0), todayCount = records.filter(r=>new Date(r.awardedAt).toDateString()===new Date().toDateString()).length, attentionCount = studentTotals.filter(s=>s.penalty>=5).length;
  function addViolation(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d=new FormData(e.currentTarget), p=violations.find(v=>v.reason===d.get("reason")); if(!p)return; setRecords(c=>[{id:crypto.randomUUID(),studentId:String(d.get("studentId")),type:"penalty",score:p.score,reason:p.reason,awardedBy:"담당교사",awardedAt:new Date().toISOString(),note:String(d.get("note")||"")},...c]); setModalOpen(false); setSaved(true); setTimeout(()=>setSaved(false),2500); }
  function exportCsv(){ const rows=[["일시","학년","반","번호","학생명","위반사항","벌점","기록자"],...records.filter(r=>r.score<0).map(r=>{const s=students.find(x=>x.id===r.studentId);return[r.awardedAt,s?.grade,s?.classNumber,s?.number,s?.name,r.reason,Math.abs(r.score),r.awardedBy]})]; const csv="\uFEFF"+rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="학교생활규정-위반내역.csv";a.click();URL.revokeObjectURL(url); }
  return <div className="min-h-screen bg-[#f5f7fb] text-slate-900">
    <button onClick={()=>setMenuOpen(true)} className="fixed left-4 top-4 z-40 rounded-xl border bg-white p-2.5 shadow-card lg:hidden" aria-label="메뉴 열기"><Menu size={21}/></button>{menuOpen&&<button className="fixed inset-0 z-40 bg-slate-950/35 lg:hidden" onClick={()=>setMenuOpen(false)} aria-label="메뉴 닫기"/>}
    <aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-[#102a43] px-5 py-6 text-white transition-transform lg:translate-x-0 ${menuOpen?"translate-x-0":"-translate-x-full"}`}><div className="flex items-center gap-3 px-2"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-400 text-[#102a43]"><GraduationCap/></div><div><p className="font-bold">우리학교 생활관리</p><p className="text-xs text-slate-300">생활규정 위반 기록 시스템</p></div><button onClick={()=>setMenuOpen(false)} className="ml-auto lg:hidden"><X/></button></div><nav className="mt-10 space-y-1.5">{nav.map(item=><button key={item.id} onClick={()=>{setView(item.id);setMenuOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold ${view===item.id?"bg-white text-[#102a43]":"text-slate-300 hover:bg-white/10 hover:text-white"}`}><item.icon size={19}/>{item.label}</button>)}</nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="text-sky-400" size={18}/>2026학년도 2학기</div><p className="mt-2 text-xs leading-5 text-slate-300">기록은 이 기기에 자동 저장됩니다.</p></div></aside>
    <main className="min-h-screen lg:pl-72"><header className="flex h-20 items-center justify-end border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><div className="text-right"><p className="text-sm font-bold">담당교사</p><p className="text-xs text-slate-500">생활안전부</p></div><div className="grid h-10 w-10 place-items-center rounded-full bg-sky-100 font-bold text-sky-800">교</div></div></header><div className="mx-auto max-w-7xl p-5 sm:p-8">
      {view==="dashboard"&&<><PageHead title="한눈에 보는 오늘의 기록" description="위반 사항을 빠르게 기록하고 관리가 필요한 학생을 확인하세요." action={<button onClick={()=>setModalOpen(true)} className="primary-btn"><Plus size={18}/>위반 사항 기록</button>}/><section className="grid gap-4 sm:grid-cols-3"><Stat label="오늘 등록" value={`${todayCount}건`} icon={Clock3} tone="blue"/><Stat label="누적 벌점" value={`${totalPenalty}점`} icon={AlertTriangle} tone="amber"/><Stat label="관리 필요" value={`${attentionCount}명`} icon={UserRound} tone="rose"/></section><section className="mt-6 grid gap-6 xl:grid-cols-5"><article className="card xl:col-span-3"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">관리 우선 학생</h2><p className="mt-1 text-sm text-slate-500">누적 벌점이 높은 순서입니다.</p></div><button onClick={()=>setView("students")} className="flex items-center text-sm font-bold text-sky-700">전체 보기<ChevronRight size={17}/></button></div><div className="mt-5 space-y-3">{studentTotals.slice(0,4).map(s=><div key={s.id} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-white font-bold shadow-sm">{s.name[0]}</div><div className="flex-1"><p className="font-bold">{s.name}</p><p className="text-xs text-slate-500">{s.grade}학년 {s.classNumber}반 {s.number}번 · 위반 {s.count}회</p></div><b className={`rounded-full px-3 py-1 text-sm ${s.penalty>=5?"bg-rose-100 text-rose-700":"bg-amber-100 text-amber-700"}`}>{s.penalty}점</b></div>)}</div></article><article className="card xl:col-span-2"><h2 className="font-extrabold">최근 위반 기록</h2><p className="mt-1 text-sm text-slate-500">최근 등록된 5건입니다.</p><div className="mt-4 divide-y">{records.filter(r=>r.score<0).slice(0,5).map(r=><div key={r.id} className="py-3"><div className="flex justify-between gap-3 text-sm"><p><StudentLabel student={students.find(s=>s.id===r.studentId)}/></p><b className="text-rose-600">-{Math.abs(r.score)}점</b></div><div className="mt-1 flex justify-between text-xs text-slate-500"><span>{r.reason}</span><time>{formatDate(r.awardedAt)}</time></div></div>)}</div></article></section></>}
      {view==="students"&&<><PageHead title="학생 관리" description="학생별 누적 벌점과 위반 횟수를 확인합니다." action={<button onClick={()=>setModalOpen(true)} className="primary-btn"><Plus size={17}/>위반 기록</button>}/><div className="mb-4 flex max-w-md items-center gap-2 rounded-xl border bg-white px-4"><Search size={18} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full py-3 text-sm outline-none" placeholder="이름, 학년 또는 반 검색"/></div><StudentTable students={filteredStudents}/></>}
      {view==="records"&&<><PageHead title="위반 내역" description="등록된 생활규정 위반 기록을 최신순으로 확인합니다." action={<button onClick={()=>setModalOpen(true)} className="primary-btn"><Plus size={17}/>새 기록</button>}/><RecordTable records={records} students={students}/></>}
      {view==="report"&&<><PageHead title="리포트 · 내보내기" description="생활지도 자료를 업무용 파일로 내려받습니다." action={<button onClick={exportCsv} className="primary-btn"><Download size={17}/>CSV 내려받기</button>}/><div className="grid gap-5 md:grid-cols-2"><div className="card"><BarChart3 className="text-sky-700"/><h2 className="mt-4 text-xl font-extrabold">현재 기록 요약</h2><p className="mt-2 text-sm leading-6 text-slate-500">학생 {students.length}명 · 위반 기록 {records.filter(r=>r.score<0).length}건 · 누적 벌점 {totalPenalty}점</p></div><div className="rounded-2xl bg-[#102a43] p-6 text-white"><FileText className="text-sky-400"/><h2 className="mt-4 text-xl font-extrabold">업무 자료로 활용</h2><p className="mt-2 text-sm leading-6 text-slate-300">CSV 파일은 엑셀에서 바로 열어 상담 및 생활지도 자료로 활용할 수 있습니다.</p></div></div></>}
      {view==="settings"&&<><PageHead title="규정 항목 설정" description="학교생활규정에 맞춘 기본 위반 항목입니다."/><div className="grid gap-3">{violations.map(v=><div key={v.reason} className="flex items-center rounded-2xl border bg-white p-5 shadow-card"><span className="rounded-lg bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{v.category}</span><p className="ml-4 flex-1 font-bold">{v.reason}</p><b className="text-rose-600">{v.score}점</b></div>)}</div></>}
    </div></main>
    {modalOpen&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold">위반 사항 기록</h2><p className="mt-1 text-sm text-slate-500">학생과 해당 규정 항목을 선택하세요.</p></div><button onClick={()=>setModalOpen(false)} aria-label="닫기"><X/></button></div><form onSubmit={addViolation} className="mt-6 space-y-5"><label className="field-label">학생<select name="studentId" className="field">{students.map(s=><option key={s.id} value={s.id}>{s.grade}학년 {s.classNumber}반 {s.number}번 {s.name}</option>)}</select></label><label className="field-label">위반 항목<select name="reason" className="field">{violations.map(v=><option key={v.reason}>{v.reason}</option>)}</select></label><label className="field-label">메모 (선택)<textarea name="note" rows={3} className="field resize-none" placeholder="상황이나 후속 조치 내용을 입력하세요."/></label><div className="flex gap-3"><button type="button" onClick={()=>setModalOpen(false)} className="flex-1 rounded-xl border py-3 text-sm font-bold">취소</button><button className="flex-1 rounded-xl bg-primary py-3 text-sm font-bold text-white">기록 저장</button></div></form></div></div>}
    {saved&&<div className="fixed bottom-6 right-6 z-[70] flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white shadow-xl"><Check size={18}/>위반 기록을 저장했습니다.</div>}
  </div>;
}
function PageHead({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <section className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-sky-700">생활지도 현황</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p></div>{action}</section>}
function Stat({label,value,icon:Icon,tone}:{label:string;value:string;icon:typeof Clock3;tone:"blue"|"amber"|"rose"}){const c={blue:"bg-sky-100 text-sky-700",amber:"bg-amber-100 text-amber-700",rose:"bg-rose-100 text-rose-700"};return <article className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-card"><div className={`grid h-12 w-12 place-items-center rounded-2xl ${c[tone]}`}><Icon size={22}/></div><div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="text-2xl font-extrabold">{value}</p></div></article>}
function Status({score}:{score:number}){return <span className={`rounded-full px-3 py-1 text-xs font-bold ${score>=5?"bg-rose-100 text-rose-700":score>0?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700"}`}>{score>=5?"상담 필요":score>0?"관찰":"양호"}</span>}
function StudentTable({students}:{students:Array<Student&{penalty:number;count:number}>}){return <div className="table-wrap"><table><thead><tr><th>학생</th><th>학급</th><th>위반 횟수</th><th>누적 벌점</th><th>상태</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td className="font-bold">{s.name}</td><td>{s.grade}학년 {s.classNumber}반 {s.number}번</td><td>{s.count}회</td><td className="font-bold text-rose-600">{s.penalty}점</td><td><Status score={s.penalty}/></td></tr>)}</tbody></table></div>}
function RecordTable({records,students}:{records:PointRecord[];students:Student[]}){return <div className="table-wrap"><table><thead><tr><th>일시</th><th>학생</th><th>위반 사항</th><th>벌점</th><th>기록자</th></tr></thead><tbody>{records.filter(r=>r.score<0).map(r=><tr key={r.id}><td className="text-slate-500">{formatDate(r.awardedAt)}</td><td><StudentLabel student={students.find(s=>s.id===r.studentId)}/></td><td className="font-semibold">{r.reason}</td><td className="font-bold text-rose-600">-{Math.abs(r.score)}점</td><td>{r.awardedBy}</td></tr>)}</tbody></table></div>}
