"use client";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { AlertTriangle, BarChart3, Check, ChevronRight, ClipboardList, Clock3, Download, FileText, Gavel, GraduationCap, LayoutDashboard, Menu, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, Trash2, UserRound, Users, X } from "lucide-react";
import { students as initialStudents, pointRecords as initialRecords } from "@/lib/mock-data";
import type { PointRecord, Student } from "@/types";

type View = "dashboard" | "students" | "records" | "byRule" | "committee" | "report" | "settings";
const nav: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "dashboard", label: "대시보드", icon: LayoutDashboard }, { id: "students", label: "학생 관리", icon: Users },
  { id: "records", label: "위반 내역", icon: ClipboardList }, { id: "byRule", label: "위반 항목별 현황", icon: BarChart3 }, { id: "committee", label: "생활교육위원회", icon: Gavel }, { id: "report", label: "리포트 · 내보내기", icon: FileText },
  { id: "settings", label: "규정 항목 설정", icon: Settings },
];
const initialViolations = [
  { id: "v-01", reason: "무단 지각", score: -1 }, { id: "v-02", reason: "무단 결과·조퇴", score: -1 },
  { id: "v-03", reason: "수업 방해", score: -1 }, { id: "v-04", reason: "교내 전자기기 무단 사용", score: -1 },
  { id: "v-05", reason: "복장·용의 규정 위반", score: -1 }, { id: "v-06", reason: "위험 물품 소지", score: -1 },
  { id: "v-07", reason: "언어폭력·모욕", score: -1 },
];
const formatDate = (value: string) => new Intl.DateTimeFormat("ko-KR", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
function readStored<T>(key:string,fallback:T):T { try { const value=localStorage.getItem(key); return value?JSON.parse(value):fallback; } catch { return fallback; } }
const demoCommitteeRecords: PointRecord[] = [
  ...Array.from({length:10},(_,i)=>({id:`demo-general-${i+1}`,studentId:"s-001",type:"penalty" as const,score:-1,reason:i%2===0?"무단 지각":"수업 방해",awardedBy:"담당교사",awardedAt:`2026-09-${String(i+1).padStart(2,"0")}T09:00:00`})),
  ...Array.from({length:2},(_,i)=>({id:`demo-device-${i+1}`,studentId:"s-002",type:"penalty" as const,score:-1,reason:"교내 전자기기 무단 사용",awardedBy:"담당교사",awardedAt:`2026-09-0${i+1}T10:00:00`})),
];
function StudentLabel({ student }: { student?: Student }) { return student ? <><strong>{student.name}</strong><span className="text-slate-400"> {student.grade}학년 {student.classNumber}반 {student.number}번</span></> : <span>삭제된 학생</span>; }

export function Dashboard() {
  const [view, setView] = useState<View>("dashboard"), [menuOpen, setMenuOpen] = useState(false), [modalOpen, setModalOpen] = useState(false), [studentModalOpen, setStudentModalOpen] = useState(false), [editingStudent, setEditingStudent] = useState<Student|null>(null), [editingRecord, setEditingRecord] = useState<PointRecord|null>(null), [saved, setSaved] = useState(false), [query, setQuery] = useState(""), [studentSearch, setStudentSearch] = useState(""), [classFilter, setClassFilter] = useState("all"), [recordClassFilter, setRecordClassFilter] = useState("all"), [recordReasonFilter, setRecordReasonFilter] = useState("all");
  const [students, setStudents] = useState<Student[]>(initialStudents), [records, setRecords] = useState<PointRecord[]>(initialRecords);
  const [violations, setViolations] = useState(initialViolations);
  const [committeeHeld, setCommitteeHeld] = useState<Record<string,boolean>>({}), [committeeDismissed, setCommitteeDismissed] = useState<string[]>([]);
  const [authenticated, setAuthenticated] = useState<boolean|null>(null), [pin, setPin] = useState(""), [pinError, setPinError] = useState(false), [editStudentSearch, setEditStudentSearch] = useState("");
  const [remoteReady, setRemoteReady] = useState(false), [syncError, setSyncError] = useState(false);
  const [pinChangeMessage,setPinChangeMessage]=useState(""), [pinChangeError,setPinChangeError]=useState(false);
  useEffect(() => { const base=readStored<PointRecord[]>("school-violation-records",initialRecords), missing=demoCommitteeRecords.filter(d=>!base.some(r=>r.id===d.id)); setRecords([...missing,...base]); }, []);
  useEffect(() => { localStorage.setItem("school-violation-records", JSON.stringify(records)); }, [records]);
  useEffect(() => { setStudents(readStored("school-students",initialStudents)); }, []);
  useEffect(() => { localStorage.setItem("school-students", JSON.stringify(students)); }, [students]);
  useEffect(() => { setViolations(readStored("school-violation-rules",initialViolations)); }, []);
  useEffect(() => { localStorage.setItem("school-violation-rules", JSON.stringify(violations)); }, [violations]);
  useEffect(() => { setCommitteeHeld(readStored("school-committee-held",{})); setCommitteeDismissed(readStored("school-committee-dismissed",[])); }, []);
  useEffect(() => { localStorage.setItem("school-committee-held",JSON.stringify(committeeHeld)); }, [committeeHeld]);
  useEffect(() => { localStorage.setItem("school-committee-dismissed",JSON.stringify(committeeDismissed)); }, [committeeDismissed]);
  useEffect(() => { fetch("/api/auth/status").then(r=>r.json()).then(d=>setAuthenticated(d.authenticated)).catch(()=>setAuthenticated(false)); }, []);
  useEffect(() => {
    if (!authenticated) return;
    let active=true;
    const load=async(initial=false)=>{ try { const response=await fetch("/api/state",{cache:"no-store"}); if(!response.ok)throw new Error(); const result=await response.json(), shared=result.data; if(shared?.students){ if(!active)return; setStudents(shared.students); setRecords(shared.records||[]); setViolations(shared.violations||initialViolations); setCommitteeHeld(shared.committeeHeld||{}); setCommitteeDismissed(shared.committeeDismissed||[]); } else if(initial) { await fetch("/api/state",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({students,records,violations,committeeHeld,committeeDismissed})}); } if(active){setRemoteReady(true);setSyncError(false);} } catch { if(active)setSyncError(true); } };
    load(true); const timer=setInterval(()=>load(false),10000); return()=>{active=false;clearInterval(timer)};
  },[authenticated]);
  async function mutateRecord(operation:Record<string,unknown>) {
    const response=await fetch("/api/state",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(operation)});
    if(!response.ok)throw new Error("동기화 실패");
    const result=await response.json();
    if(Array.isArray(result.data?.records))setRecords(result.data.records);
    setSyncError(false);
  }
  useEffect(() => { if(!remoteReady)return; const timer=setTimeout(()=>{fetch("/api/state",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"state:merge",data:{students,violations,committeeHeld,committeeDismissed}})}).then(r=>{if(!r.ok)throw new Error();setSyncError(false)}).catch(()=>setSyncError(true));},500); return()=>clearTimeout(timer); },[students,violations,committeeHeld,committeeDismissed,remoteReady]);
  const studentTotals = useMemo(() => students.map(student => ({ ...student, penalty: 0, count: records.filter(r => r.studentId === student.id && r.score < 0).length, deviceCount: records.filter(r => r.studentId === student.id && r.score < 0 && r.reason === "교내 전자기기 무단 사용").length })).sort((a,b) => b.count-a.count), [records, students]);
  const filteredStudents = studentTotals.filter(s => (`${s.name} ${s.grade}-${s.classNumber} ${s.number}`.includes(query)) && (classFilter === "all" || classFilter === `${s.grade}-${s.classNumber}`));
  const committeeStudents = studentTotals.filter(s=>(s.count>=10||s.deviceCount>=2)&&!committeeDismissed.includes(s.id));
  const filteredRecords = records.filter(r=>r.score<0).filter(r=>{const s=students.find(x=>x.id===r.studentId); return (recordClassFilter==="all"||`${s?.grade}-${s?.classNumber}`===recordClassFilter)&&(recordReasonFilter==="all"||r.reason===recordReasonFilter);});
  const totalViolations = records.filter(r=>r.score<0).length, todayCount = records.filter(r=>r.score<0 && new Date(r.awardedAt).toDateString()===new Date().toDateString()).length, attentionCount = studentTotals.filter(s=>s.count>=7).length;
  async function addViolation(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d=new FormData(e.currentTarget), p=violations.find(v=>v.reason===d.get("reason")); if(!p)return; const record={id:crypto.randomUUID(),studentId:String(d.get("studentId")),type:"penalty" as const,score:p.score,reason:p.reason,awardedBy:String(d.get("awardedBy")).trim(),awardedAt:new Date().toISOString(),note:String(d.get("note")||"")}; try { await mutateRecord({type:"record:add",record}); setModalOpen(false); setStudentSearch(""); setSaved(true); setTimeout(()=>setSaved(false),2500); } catch { setSyncError(true); window.alert("기록을 저장하지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주세요."); } }
  async function updateRecord(e:FormEvent<HTMLFormElement>) { e.preventDefault(); if(!editingRecord)return; const d=new FormData(e.currentTarget), record={...editingRecord,studentId:String(d.get("studentId")),reason:String(d.get("reason")),awardedBy:String(d.get("awardedBy")).trim(),note:String(d.get("note")||"")}; try { await mutateRecord({type:"record:update",record}); setEditingRecord(null); setEditStudentSearch(""); setSaved(true); setTimeout(()=>setSaved(false),2500); } catch { setSyncError(true); window.alert("수정 내용을 저장하지 못했습니다. 다시 시도해 주세요."); } }
  async function deleteRecord(record:PointRecord) { if(!window.confirm(`${students.find(s=>s.id===record.studentId)?.name||"해당 학생"}의 ${record.reason} 기록을 삭제할까요?`))return; try { await mutateRecord({type:"record:delete",id:record.id}); } catch { setSyncError(true); window.alert("기록을 삭제하지 못했습니다. 다시 시도해 주세요."); } }
  function addStudent(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d=new FormData(e.currentTarget), grade=Number(d.get("grade")), classNumber=Number(d.get("classNumber")); if(grade>1&&classNumber===4){window.alert("2·3학년은 1반부터 3반까지만 등록할 수 있습니다.");return;} setStudents(c=>[...c,{id:crypto.randomUUID(),grade,classNumber,number:Number(d.get("number")),name:String(d.get("name")),createdAt:new Date().toISOString().slice(0,10)}].sort((a,b)=>a.grade-b.grade||a.classNumber-b.classNumber||a.number-b.number)); setStudentModalOpen(false); setSaved(true); setTimeout(()=>setSaved(false),2500); }
  function updateStudent(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if(!editingStudent)return; const d=new FormData(e.currentTarget), grade=Number(d.get("grade")), classNumber=Number(d.get("classNumber")); if(grade>1&&classNumber===4){window.alert("2·3학년은 1반부터 3반까지만 등록할 수 있습니다.");return;} setStudents(c=>c.map(s=>s.id===editingStudent.id?{...s,grade,classNumber,number:Number(d.get("number")),name:String(d.get("name"))}:s).sort((a,b)=>a.grade-b.grade||a.classNumber-b.classNumber||a.number-b.number)); setEditingStudent(null); setSaved(true); setTimeout(()=>setSaved(false),2500); }
  function deleteStudent(student:Student) { if(!window.confirm(`${student.name} 학생을 명단에서 삭제할까요? 해당 학생의 위반 기록도 함께 삭제됩니다.`))return; setStudents(c=>c.filter(s=>s.id!==student.id)); setRecords(c=>c.filter(r=>r.studentId!==student.id)); }
  async function importRoster(e:ChangeEvent<HTMLInputElement>) { const file=e.target.files?.[0]; e.target.value=""; if(!file)return; try { const data=await file.arrayBuffer(), workbook=XLSX.read(data), sheet=workbook.Sheets[workbook.SheetNames[0]], rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""}); const imported=rows.map((row,i)=>({id:`import-${Date.now()}-${i}`,grade:Number(row["학년"]??row["grade"]),classNumber:Number(row["반"]??row["학급"]??row["class"]),number:Number(row["번호"]??row["number"]),name:String(row["이름"]??row["성명"]??row["name"]).trim(),createdAt:new Date().toISOString().slice(0,10)})).filter(s=>s.name&&[1,2,3].includes(s.grade)&&s.classNumber>=1&&s.classNumber<=(s.grade===1?4:3)&&s.number>=1); if(!imported.length){window.alert("명단을 읽지 못했습니다. 첫 행에 학년, 반, 번호, 이름 열이 있는지 확인해 주세요.");return;} if(!window.confirm(`${imported.length}명의 명단으로 현재 학생 명단을 교체하고 기존 위반 기록을 초기화할까요?`))return; setStudents(imported.sort((a,b)=>a.grade-b.grade||a.classNumber-b.classNumber||a.number-b.number)); setRecords([]); setClassFilter("all"); setSaved(true); setTimeout(()=>setSaved(false),2500); } catch { window.alert("엑셀 파일을 읽는 중 문제가 발생했습니다. .xlsx 또는 .xls 파일인지 확인해 주세요."); } }
  function downloadRosterTemplate() { const sheet=XLSX.utils.aoa_to_sheet([["학년","반","번호","이름"],[1,1,1,"홍길동"]]); sheet["!cols"]=[{wch:10},{wch:10},{wch:10},{wch:18}]; const workbook=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook,sheet,"학생명단"); XLSX.writeFile(workbook,"장흥중학교-학생명단-서식.xlsx"); }
  function removeCommitteeStudent(student:Student) { if(!window.confirm(`${student.name} 학생을 생활교육위원회 대상 목록에서 삭제할까요? 위반 기록은 유지됩니다.`))return; setCommitteeDismissed(c=>[...c,student.id]); }
  async function loginWithPin(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin})}); if(response.ok){setAuthenticated(true);setPinError(false)}else{setPinError(true);setPin("")} }
  async function changePin(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const form=e.currentTarget,d=new FormData(form),newPin=String(d.get("newPin")),confirmPin=String(d.get("confirmPin")); setPinChangeMessage(""); if(newPin!==confirmPin){setPinChangeError(true);setPinChangeMessage("새 PIN 확인 값이 일치하지 않습니다.");return;} const response=await fetch("/api/auth/change-pin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({adminPassword:String(d.get("adminPassword")),newPin})}); const result=await response.json(); if(!response.ok){setPinChangeError(true);setPinChangeMessage(result.error||"PIN을 변경하지 못했습니다.");return;} form.reset();setPinChangeError(false);setPinChangeMessage("PIN이 변경되었습니다. 다른 선생님들은 새 PIN으로 다시 접속해야 합니다."); }
  function advanceSchoolYear() { if(!window.confirm("학년도를 전환하면 3학년 명단과 모든 위반 기록이 삭제되고, 1·2학년은 한 학년씩 진급합니다. 계속할까요?"))return; setStudents(c=>c.filter(s=>s.grade<3).map(s=>({...s,grade:s.grade+1,classNumber:Math.min(s.classNumber,3)}))); setRecords([]); setClassFilter("all"); setSaved(true); setTimeout(()=>setSaved(false),2500); }
  function addRule(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form=e.currentTarget, d=new FormData(form), reason=String(d.get("rule")).trim(); if(!reason)return; setViolations(c=>[...c,{id:crypto.randomUUID(),reason,score:-1}]); form.reset(); }
  function updateRule(id:string, reason:string) { setViolations(c=>c.map(v=>v.id===id?{...v,reason}:v)); }
  function deleteRule(id:string) { const rule=violations.find(v=>v.id===id); if(!rule||!window.confirm(`\"${rule.reason}\" 규정 항목을 삭제할까요? 기존 위반 기록은 유지됩니다.`))return; setViolations(c=>c.filter(v=>v.id!==id)); }
  function exportCsv(){ const rows=[["일시","학년","반","번호","학생명","위반사항","기록자"],...records.filter(r=>r.score<0).map(r=>{const s=students.find(x=>x.id===r.studentId);return[r.awardedAt,s?.grade,s?.classNumber,s?.number,s?.name,r.reason,r.awardedBy]})]; const csv="\uFEFF"+rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="장흥중학교-생활규정-위반내역.csv";a.click();URL.revokeObjectURL(url); }
  if(authenticated===null)return <div className="grid min-h-screen place-items-center bg-[#102a43] text-sm font-bold text-white">접속 확인 중...</div>;
  if(!authenticated)return <div className="grid min-h-screen place-items-center bg-[#102a43] p-5"><div className="w-full max-w-sm rounded-3xl bg-white p-8 shadow-2xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-sky-400 text-[#102a43]"><GraduationCap size={30}/></div><h1 className="mt-5 text-center text-2xl font-extrabold">장흥중학교 생활관리</h1><p className="mt-2 text-center text-sm text-slate-500">교사 공용 PIN 번호를 입력해 주세요.</p><form onSubmit={loginWithPin} className="mt-6"><input value={pin} onChange={e=>{setPin(e.target.value);setPinError(false)}} inputMode="numeric" type="password" autoFocus required className="field text-center text-xl tracking-[0.4em]" placeholder="PIN"/>{pinError&&<p className="mt-2 text-center text-sm font-bold text-rose-600">PIN 번호가 올바르지 않습니다.</p>}<button className="mt-4 w-full rounded-xl bg-primary py-3.5 text-sm font-bold text-white">입장하기</button></form></div></div>;
  return <div className="min-h-screen bg-[#f5f7fb] text-slate-900">
    <button onClick={()=>setMenuOpen(true)} className="fixed left-4 top-4 z-40 rounded-xl border bg-white p-2.5 shadow-card lg:hidden" aria-label="메뉴 열기"><Menu size={21}/></button>{menuOpen&&<button className="fixed inset-0 z-40 bg-slate-950/35 lg:hidden" onClick={()=>setMenuOpen(false)} aria-label="메뉴 닫기"/>}
    <aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-[#102a43] px-5 py-6 text-white transition-transform lg:translate-x-0 ${menuOpen?"translate-x-0":"-translate-x-full"}`}><div className="flex items-center gap-3 px-2"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-400 text-[#102a43]"><GraduationCap/></div><div><p className="font-bold">장흥중학교</p><p className="text-xs text-slate-300">생활규정 위반 기록 시스템</p></div><button onClick={()=>setMenuOpen(false)} className="ml-auto lg:hidden"><X/></button></div><nav className="mt-10 space-y-1.5">{nav.map(item=><button key={item.id} onClick={()=>{setView(item.id);setMenuOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold ${view===item.id?"bg-white text-[#102a43]":"text-slate-300 hover:bg-white/10 hover:text-white"}`}><item.icon size={19}/>{item.label}</button>)}</nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck className={syncError?"text-rose-400":"text-sky-400"} size={18}/>{syncError?"동기화 확인 필요":remoteReady?"공용 DB 연결됨":"공용 DB 연결 중"}</div><p className="mt-2 text-xs leading-5 text-slate-300">교사들과 데이터가 자동 공유됩니다.</p></div></aside>
    <main className="min-h-screen lg:pl-72"><header className="flex h-20 items-center justify-end border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><div className="text-right"><p className="text-sm font-bold">담당교사</p><p className="text-xs text-slate-500">생활안전부</p></div><div className="grid h-10 w-10 place-items-center rounded-full bg-sky-100 font-bold text-sky-800">교</div></div></header><div className="mx-auto max-w-7xl p-5 sm:p-8">
      {view==="dashboard"&&<><PageHead title="한눈에 보는 오늘의 기록" description="위반 사항을 빠르게 기록하고 관리가 필요한 학생을 확인하세요." action={<button onClick={()=>setModalOpen(true)} className="primary-btn"><Plus size={18}/>위반 사항 기록</button>}/><section className="grid gap-4 sm:grid-cols-3"><Stat label="오늘 등록" value={`${todayCount}건`} icon={Clock3} tone="blue"/><Stat label="누적 위반" value={`${totalViolations}회`} icon={AlertTriangle} tone="amber"/><Stat label="관리 필요" value={`${attentionCount}명`} icon={UserRound} tone="rose"/></section><section className="mt-6 grid gap-6 xl:grid-cols-5"><article className="card xl:col-span-3"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">관리 우선 학생</h2><p className="mt-1 text-sm text-slate-500">위반 횟수가 많은 순서입니다.</p></div><button onClick={()=>setView("students")} className="flex items-center text-sm font-bold text-sky-700">전체 보기<ChevronRight size={17}/></button></div><div className="mt-5 space-y-3">{studentTotals.slice(0,4).map(s=><div key={s.id} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-white font-bold shadow-sm">{s.name[0]}</div><div className="flex-1"><p className="font-bold">{s.name}</p><p className="text-xs text-slate-500">{s.grade}학년 {s.classNumber}반 {s.number}번</p></div><b className={`rounded-full px-3 py-1 text-sm ${s.count>=3?"bg-rose-100 text-rose-700":"bg-amber-100 text-amber-700"}`}>{s.count}회</b></div>)}</div></article><article className="card xl:col-span-2"><h2 className="font-extrabold">최근 위반 기록</h2><p className="mt-1 text-sm text-slate-500">최근 등록된 5건입니다.</p><div className="mt-4 divide-y">{records.filter(r=>r.score<0).slice(0,5).map(r=><div key={r.id} className="py-3"><div className="flex justify-between gap-3 text-sm"><p><StudentLabel student={students.find(s=>s.id===r.studentId)}/></p><b className="text-rose-600">1회</b></div><div className="mt-1 flex justify-between text-xs text-slate-500"><span>{r.reason}</span><time>{formatDate(r.awardedAt)}</time></div></div>)}</div></article></section></>}
      {view==="students"&&<><PageHead title="학생 명단 · 학급별 현황" description="전체 학생 명단과 각 반의 위반 현황을 확인합니다." action={<div className="flex flex-wrap gap-2"><button onClick={downloadRosterTemplate} className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><Download className="inline" size={17}/> 엑셀 서식</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm font-bold text-sky-800"><FileText size={17}/>엑셀 명단 불러오기<input type="file" accept=".xlsx,.xls" onChange={importRoster} className="sr-only"/></label><button onClick={advanceSchoolYear} className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800"><RefreshCw className="inline" size={17}/> 학년도 전환</button><button onClick={()=>setStudentModalOpen(true)} className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><Plus className="inline" size={17}/> 학생 추가</button><button onClick={()=>setModalOpen(true)} className="primary-btn"><Plus size={17}/>위반 기록</button></div>}/><div className="mb-4 rounded-xl border border-sky-100 bg-sky-50 px-4 py-3 text-sm text-sky-900">엑셀 첫 행의 열 이름을 <b>학년, 반, 번호, 이름</b>으로 작성해 주세요. 불러오면 현재 명단과 위반 기록이 새 학년도 기준으로 교체됩니다.</div><div className="mb-5 flex flex-wrap gap-2"><button onClick={()=>setClassFilter("all")} className={`filter-chip ${classFilter==="all"?"filter-chip-active":""}`}>전체 {students.length}명</button>{[1,2,3].flatMap(g=>Array.from({length:g===1?4:3},(_,i)=>`${g}-${i+1}`)).map(c=><button key={c} onClick={()=>setClassFilter(c)} className={`filter-chip ${classFilter===c?"filter-chip-active":""}`}>{c.replace("-","학년 ")}반 · {studentTotals.filter(s=>`${s.grade}-${s.classNumber}`===c).reduce((n,s)=>n+s.count,0)}회</button>)}</div><div className="mb-4 flex max-w-md items-center gap-2 rounded-xl border bg-white px-4"><Search size={18} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full py-3 text-sm outline-none" placeholder="학생 이름 또는 번호 검색"/></div><StudentTable students={filteredStudents} onEdit={setEditingStudent} onDelete={deleteStudent}/></>}
      {view==="records"&&<><PageHead title="위반 내역" description="반과 위반 항목을 선택해 기록과 메모를 확인합니다." action={<button onClick={()=>setModalOpen(true)} className="primary-btn"><Plus size={17}/>새 기록</button>}/><div className="mb-4 flex flex-wrap gap-3"><select value={recordClassFilter} onChange={e=>setRecordClassFilter(e.target.value)} className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><option value="all">전체 학급</option>{[1,2,3].flatMap(g=>Array.from({length:g===1?4:3},(_,i)=>`${g}-${i+1}`)).map(c=><option key={c} value={c}>{c.replace("-","학년 ")}반</option>)}</select><select value={recordReasonFilter} onChange={e=>setRecordReasonFilter(e.target.value)} className="rounded-xl border bg-white px-4 py-3 text-sm font-bold"><option value="all">전체 위반 항목</option>{violations.map(v=><option key={v.id} value={v.reason}>{v.reason}</option>)}</select><span className="self-center text-sm font-bold text-slate-500">{filteredRecords.length}건</span></div><RecordTable records={filteredRecords} students={students} onEdit={setEditingRecord} onDelete={deleteRecord}/></>}
      {view==="byRule"&&<><PageHead title="위반 항목별 현황" description="각 위반 항목의 발생 횟수와 관련 학생을 확인합니다."/><div className="grid gap-4 md:grid-cols-2">{violations.map(v=>{const matched=records.filter(r=>r.score<0&&r.reason===v.reason),names=[...new Set(matched.map(r=>students.find(s=>s.id===r.studentId)?.name).filter(Boolean))];return <article key={v.id} className="card"><div className="flex items-start justify-between gap-4"><div><h2 className="font-extrabold">{v.reason}</h2><p className="mt-2 text-sm text-slate-500">{names.length?names.join(", "):"해당 학생 없음"}</p></div><span className="rounded-full bg-rose-100 px-3 py-1 text-sm font-extrabold text-rose-700">{matched.length}회</span></div></article>})}</div></>}
      {view==="committee"&&<><PageHead title="생활교육위원회 대상" description="위원회 개최 여부를 기록하고 대상 목록을 관리합니다."/><div className="mb-5 grid gap-4 sm:grid-cols-2"><Stat label="위원회 대상 학생" value={`${committeeStudents.length}명`} icon={Gavel} tone="rose"/><Stat label="개최 완료" value={`${committeeStudents.filter(s=>committeeHeld[s.id]).length}명`} icon={Check} tone="blue"/></div><div className="table-wrap"><table><thead><tr><th>학생</th><th>학급</th><th>전체 위반</th><th>전자기기 위반</th><th>위원회 대상 사유</th><th>개최 여부</th><th>관리</th></tr></thead><tbody>{committeeStudents.map(s=><tr key={s.id}><td className="font-bold">{s.name}</td><td>{s.grade}학년 {s.classNumber}반 {s.number}번</td><td className="font-bold">{s.count}회</td><td className="font-bold text-rose-600">{s.deviceCount}회</td><td><div className="flex flex-wrap gap-2">{s.count>=10&&<span className="rounded-full bg-rose-100 px-3 py-1 text-xs font-bold text-rose-700">누적 위반 10회 이상</span>}{s.deviceCount>=2&&<span className="rounded-full bg-purple-100 px-3 py-1 text-xs font-bold text-purple-700">전자기기 위반 2회 이상</span>}</div></td><td><label className="inline-flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={!!committeeHeld[s.id]} onChange={e=>setCommitteeHeld(c=>({...c,[s.id]:e.target.checked}))} className="h-4 w-4 accent-sky-700"/>{committeeHeld[s.id]?"개최 완료":"미개최"}</label></td><td><button onClick={()=>removeCommitteeStudent(s)} className="rounded-lg border border-rose-200 p-2 text-rose-600 hover:bg-rose-50" aria-label={`${s.name} 위원회 목록에서 삭제`}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{committeeStudents.length===0&&<div className="p-12 text-center"><Gavel className="mx-auto text-slate-300" size={32}/><p className="mt-3 font-bold text-slate-600">현재 위원회 대상 학생이 없습니다.</p><p className="mt-1 text-sm text-slate-400">위반 기록이 기준에 도달하면 자동으로 표시됩니다.</p></div>}</div></>}
      {view==="report"&&<><PageHead title="리포트 · 내보내기" description="생활지도 자료를 업무용 파일로 내려받습니다." action={<button onClick={exportCsv} className="primary-btn"><Download size={17}/>CSV 내려받기</button>}/><div className="grid gap-5 md:grid-cols-2"><div className="card"><BarChart3 className="text-sky-700"/><h2 className="mt-4 text-xl font-extrabold">현재 기록 요약</h2><p className="mt-2 text-sm leading-6 text-slate-500">학생 {students.length}명 · 누적 위반 {totalViolations}회 · 관리 필요 {attentionCount}명</p></div><div className="rounded-2xl bg-[#102a43] p-6 text-white"><FileText className="text-sky-400"/><h2 className="mt-4 text-xl font-extrabold">업무 자료로 활용</h2><p className="mt-2 text-sm leading-6 text-slate-300">CSV 파일은 엑셀에서 바로 열어 상담 및 생활지도 자료로 활용할 수 있습니다.</p></div></div></>}
      {view==="settings"&&<><PageHead title="규정 항목 설정" description="위반 항목과 교사 공용 PIN을 관리합니다."/><section className="mb-7 grid gap-6 xl:grid-cols-5"><div className="xl:col-span-3"><form onSubmit={addRule} className="mb-5 flex gap-2"><input name="rule" required className="field !mt-0" placeholder="새 위반 항목 입력"/><button className="primary-btn shrink-0"><Plus size={17}/>항목 추가</button></form><div className="grid gap-3">{violations.map(v=><div key={v.id} className="flex items-center gap-3 rounded-2xl border bg-white p-4 shadow-card"><input value={v.reason} onChange={e=>updateRule(v.id,e.target.value)} className="min-w-0 flex-1 rounded-xl border border-transparent px-3 py-2 font-bold outline-none hover:border-slate-200 focus:border-sky-500 focus:ring-2 focus:ring-sky-100" aria-label="규정 항목명"/><span className="shrink-0 text-sm font-bold text-slate-500">1회</span><button onClick={()=>deleteRule(v.id)} className="rounded-xl p-2.5 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label={`${v.reason} 삭제`}><Trash2 size={18}/></button></div>)}</div>{violations.length===0&&<div className="card text-center text-sm text-slate-500">등록된 규정 항목이 없습니다. 위에서 새 항목을 추가하세요.</div>}</div><form onSubmit={changePin} className="card h-fit xl:col-span-2"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-amber-700"><ShieldCheck size={22}/></div><div><h2 className="font-extrabold">공용 PIN 변경</h2><p className="mt-1 text-xs text-slate-500">관리자 비밀번호 확인 후 변경됩니다.</p></div></div><label className="field-label mt-5">관리자 비밀번호<input name="adminPassword" type="password" required autoComplete="current-password" className="field" placeholder="관리자 비밀번호"/></label><label className="field-label mt-4">새 PIN<input name="newPin" type="password" inputMode="numeric" pattern="[0-9]{4,12}" minLength={4} maxLength={12} required className="field" placeholder="숫자 4~12자리"/></label><label className="field-label mt-4">새 PIN 확인<input name="confirmPin" type="password" inputMode="numeric" pattern="[0-9]{4,12}" minLength={4} maxLength={12} required className="field" placeholder="새 PIN 다시 입력"/></label>{pinChangeMessage&&<p className={`mt-4 rounded-xl px-4 py-3 text-sm font-bold ${pinChangeError?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{pinChangeMessage}</p>}<button className="mt-5 w-full rounded-xl bg-[#102a43] py-3 text-sm font-bold text-white">PIN 변경하기</button><p className="mt-3 text-xs leading-5 text-slate-500">변경 즉시 기존 PIN은 사용할 수 없으며, 다른 기기의 로그인도 해제됩니다.</p></form></section></>}
    </div></main>
    {modalOpen&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold">위반 사항 기록</h2><p className="mt-1 text-sm text-slate-500">학생을 검색한 뒤 규정 항목을 선택하세요.</p></div><button onClick={()=>{setModalOpen(false);setStudentSearch("")}} aria-label="닫기"><X/></button></div><form onSubmit={addViolation} className="mt-6 space-y-5"><label className="field-label">학생 검색<div className="relative"><Search className="absolute left-4 top-5 text-slate-400" size={17}/><input value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} className="field pl-11" placeholder="이름, 학년-반 또는 번호"/></div></label><label className="field-label">학생<select name="studentId" required className="field">{students.filter(s=>`${s.name} ${s.grade}-${s.classNumber} ${s.number}`.includes(studentSearch)).map(s=><option key={s.id} value={s.id}>{s.grade}학년 {s.classNumber}반 {s.number}번 {s.name}</option>)}</select></label><label className="field-label">위반 항목<select name="reason" className="field">{violations.map(v=><option key={v.reason}>{v.reason}</option>)}</select></label><label className="field-label">기록자<input name="awardedBy" required className="field" placeholder="교사 이름"/></label><label className="field-label">메모 (선택)<textarea name="note" rows={3} className="field resize-none" placeholder="상황이나 후속 조치 내용을 입력하세요."/></label><div className="flex gap-3"><button type="button" onClick={()=>{setModalOpen(false);setStudentSearch("")}} className="flex-1 rounded-xl border py-3 text-sm font-bold">취소</button><button className="flex-1 rounded-xl bg-primary py-3 text-sm font-bold text-white">기록 저장</button></div></form></div></div>}
    {editingRecord&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold">위반 기록 수정</h2><p className="mt-1 text-sm text-slate-500">학생을 검색하고 기록 내용을 수정할 수 있습니다.</p></div><button onClick={()=>{setEditingRecord(null);setEditStudentSearch("")}} aria-label="닫기"><X/></button></div><form onSubmit={updateRecord} className="mt-6 space-y-5"><label className="field-label">학생 검색<div className="relative"><Search className="absolute left-4 top-5 text-slate-400" size={17}/><input value={editStudentSearch} onChange={e=>setEditStudentSearch(e.target.value)} className="field pl-11" placeholder="이름, 학년-반 또는 번호"/></div></label><label className="field-label">학생<select name="studentId" defaultValue={editingRecord.studentId} className="field">{students.filter(s=>!editStudentSearch||`${s.name} ${s.grade}-${s.classNumber} ${s.number}`.includes(editStudentSearch)||s.id===editingRecord.studentId).map(s=><option key={s.id} value={s.id}>{s.grade}학년 {s.classNumber}반 {s.number}번 {s.name}</option>)}</select></label><label className="field-label">위반 항목<select name="reason" defaultValue={editingRecord.reason} className="field">{violations.map(v=><option key={v.id} value={v.reason}>{v.reason}</option>)}</select></label><label className="field-label">기록자<input name="awardedBy" required defaultValue={editingRecord.awardedBy} className="field"/></label><label className="field-label">메모<textarea name="note" rows={3} defaultValue={editingRecord.note} className="field resize-none"/></label><div className="flex gap-3"><button type="button" onClick={()=>{setEditingRecord(null);setEditStudentSearch("")}} className="flex-1 rounded-xl border py-3 text-sm font-bold">취소</button><button className="flex-1 rounded-xl bg-primary py-3 text-sm font-bold text-white">수정 저장</button></div></form></div></div>}
    {studentModalOpen&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold">학생 추가</h2><p className="mt-1 text-sm text-slate-500">학년, 반, 번호와 이름을 입력하세요.</p></div><button onClick={()=>setStudentModalOpen(false)} aria-label="닫기"><X/></button></div><form onSubmit={addStudent} className="mt-6 space-y-5"><div className="grid grid-cols-3 gap-3"><label className="field-label">학년<select name="grade" className="field">{[1,2,3].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-label">반<select name="classNumber" className="field">{[1,2,3,4].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-label">번호<input name="number" type="number" min="1" required className="field"/></label></div><label className="field-label">이름<input name="name" required className="field" placeholder="학생 이름"/></label><div className="flex gap-3"><button type="button" onClick={()=>setStudentModalOpen(false)} className="flex-1 rounded-xl border py-3 text-sm font-bold">취소</button><button className="flex-1 rounded-xl bg-primary py-3 text-sm font-bold text-white">학생 추가</button></div></form></div></div>}
    {editingStudent&&<div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold">학생 정보 수정</h2><p className="mt-1 text-sm text-slate-500">학년, 반, 번호 또는 이름을 수정하세요.</p></div><button onClick={()=>setEditingStudent(null)} aria-label="닫기"><X/></button></div><form onSubmit={updateStudent} className="mt-6 space-y-5"><div className="grid grid-cols-3 gap-3"><label className="field-label">학년<select name="grade" defaultValue={editingStudent.grade} className="field">{[1,2,3].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-label">반<select name="classNumber" defaultValue={editingStudent.classNumber} className="field">{[1,2,3,4].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-label">번호<input name="number" type="number" min="1" required defaultValue={editingStudent.number} className="field"/></label></div><label className="field-label">이름<input name="name" required defaultValue={editingStudent.name} className="field"/></label><div className="flex gap-3"><button type="button" onClick={()=>setEditingStudent(null)} className="flex-1 rounded-xl border py-3 text-sm font-bold">취소</button><button className="flex-1 rounded-xl bg-primary py-3 text-sm font-bold text-white">수정 저장</button></div></form></div></div>}
    {saved&&<div className="fixed bottom-6 right-6 z-[70] flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white shadow-xl"><Check size={18}/>위반 기록을 저장했습니다.</div>}
  </div>;
}
function PageHead({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <section className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-sky-700">생활지도 현황</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p></div>{action}</section>}
function Stat({label,value,icon:Icon,tone}:{label:string;value:string;icon:typeof Clock3;tone:"blue"|"amber"|"rose"}){const c={blue:"bg-sky-100 text-sky-700",amber:"bg-amber-100 text-amber-700",rose:"bg-rose-100 text-rose-700"};return <article className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-card"><div className={`grid h-12 w-12 place-items-center rounded-2xl ${c[tone]}`}><Icon size={22}/></div><div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="text-2xl font-extrabold">{value}</p></div></article>}
function Status({count,deviceCount=0}:{count:number;deviceCount?:number}){const committee=count>=10||deviceCount>=2;return <span className={`rounded-full px-3 py-1 text-xs font-bold ${committee?"bg-purple-100 text-purple-700":count>=7?"bg-rose-100 text-rose-700":count>=4?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700"}`}>{committee?"위원회 대상":count>=7?"위험":count>=4?"관찰":"양호"}</span>}
function StudentTable({students,onEdit,onDelete}:{students:Array<Student&{penalty:number;count:number;deviceCount:number}>;onEdit:(student:Student)=>void;onDelete:(student:Student)=>void}){return <div className="table-wrap"><table><thead><tr><th>학생</th><th>학년</th><th>반</th><th>번호</th><th>전체 위반</th><th>전자기기 위반</th><th>상태</th><th>관리</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td className="font-bold">{s.name}</td><td>{s.grade}학년</td><td>{s.classNumber}반</td><td>{s.number}번</td><td className="font-bold text-rose-600">{s.count}회</td><td className={`font-bold ${s.deviceCount>=2?"text-purple-700":"text-slate-600"}`}>{s.deviceCount}회{s.deviceCount>=2&&<span className="ml-2 rounded-full bg-purple-100 px-2 py-1 text-xs text-purple-700">위원회</span>}</td><td><Status count={s.count} deviceCount={s.deviceCount}/></td><td><div className="flex gap-2"><button onClick={()=>onEdit(s)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50"><Pencil size={14}/>수정</button><button onClick={()=>onDelete(s)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50"><Trash2 size={14}/>삭제</button></div></td></tr>)}</tbody></table>{students.length===0&&<p className="p-10 text-center text-sm text-slate-500">해당 학급에 등록된 학생이 없습니다.</p>}</div>}
function RecordTable({records,students,onEdit,onDelete}:{records:PointRecord[];students:Student[];onEdit:(record:PointRecord)=>void;onDelete:(record:PointRecord)=>void}){return <div className="table-wrap"><table><thead><tr><th>일시</th><th>학생</th><th>위반 사항</th><th>메모</th><th>기록자</th><th>관리</th></tr></thead><tbody>{records.filter(r=>r.score<0).map(r=><tr key={r.id}><td className="text-slate-500">{formatDate(r.awardedAt)}</td><td><StudentLabel student={students.find(s=>s.id===r.studentId)}/></td><td className="font-semibold">{r.reason}</td><td className="max-w-xs whitespace-normal text-slate-600">{r.note||"-"}</td><td>{r.awardedBy}</td><td><div className="flex gap-2"><button onClick={()=>onEdit(r)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50"><Pencil size={14}/>수정</button><button onClick={()=>onDelete(r)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50"><Trash2 size={14}/>삭제</button></div></td></tr>)}</tbody></table>{records.length===0&&<p className="p-10 text-center text-sm text-slate-500">조건에 맞는 위반 기록이 없습니다.</p>}</div>}
